version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - app
        container_name: project_nginx
        networks:
            - pheo

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: project_app
        restart: always
        depends_on:
            - db
        networks:
            - pheo

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        container_name: project_db
        networks:
            - pheo

networks:
    pheo:
        driver: bridge
